### GET get accounts list
// @no-log
@customerName=Herry
GET http://localhost:8080/api/customer/{{customerName}}/getAccounts

> {%
    client.log("Response: ", response);
    client.test("Response is 200 OK", function() {
        client.assert(response.status === 200, "Expected response status is 200 OK, but received " + response.status);
    })
%}
###